app_name = universal-website-project-template
app_version = 1.0.0

runmode = dev
autorender = true
copyrequestbody = true
EnableDocs = true

[dev]
httpport = 8080
recoverpanic = true
gzip = false
SessionOn = true
SessionProvider = file
SessionProviderConfig = ./data/sessions
SessionName = besession
SessionGCMaxLifetime = 3600

[prod]
httpport = 8080
recoverpanic = false
gzip = true
SessionOn = true
SessionProvider = redis
SessionProviderConfig = 127.0.0.1:6379
SessionName = besession
SessionGCMaxLifetime = 3600

[test]
httpport = 8080
recoverpanic = false
gzip = false
SessionOn = true
SessionProvider = file
SessionProviderConfig = ./data/sessions
